### ISSUE TITLE
Debugger entered--Lisp error: (void-function org-zettel-ref-generate-id)

### ISSUE THREAD

**Issue by dingtele** [yibie/org-zettel-ref-mode#13]
when configured with option 'normal, run init command triggered 'void function org-zettel-ref-generate-id' error

once i changed the option to 'denote, everything worked fine

config that would produce the error:

```
(use-package org-zettel-ref-mode
  :ensure t
  :vc (:fetcher github :repo "yibie/org-zettel-ref-mode")
  :init 
  (setq org-zettel-ref-mode-type 'normal)
  (setq org-zettel-ref-overview-directory "~/Dropbox/org/book-notes")
)
```

**Comment by yibie** [comment]
It's done. Test it, and tell me if it works.
