### ISSUE TITLE
Put it on melpa

### ISSUE THREAD

**Issue by meritamen** [yibie/org-zettel-ref-mode#4]
First of all, thank you for this package, it's awesome!

I've installed it manually and giving it a try. So far so good.

However, I wonder if it could be added to Melpa? I can imagine it benefiting lots of people.

**Comment by yibie** [comment]
Good idea. I will put on melpa as soon as possible. 
And I will let you know.

**Comment by dmitrym0** [comment]
You can use the following recipe with straight:

```elisp
  (use-package org-zettel-ref-mode
    :straight (:host github :repo "yibie/org-zettel-ref-mode")
    :ensure t  ; If installed via package manager
    :init
    (setq org-zettel-ref-overview-directory "~/org-roam/")
    :config
    (setq org-zettel-ref-quick-markup-key "C-c m"))
```
